### ISSUE TITLE
replace Moment.js with date-fns

### ISSUE THREAD

**Issue by gasolin** [umbertoghio/expo-custom-updater#2]
https://momentjs.com/docs/#/-project-status/
`Recently, Chrome Dev Tools started showing recommendations for replacing Moment for the size alone. We generally support this move.`

**Comment by umbertoghio** [comment]
Indeed I just used moment.unix as I had it in my main project and moved the code.
On a second thought I can just do `Math.floor(Date.now() / 1000)` to get the same effect.
Adding the change in d3d1ef59c2291dc101f856b38ad23b4b7cf1e299
