### ISSUE TITLE
skipTimeCheck param is not used in isAppUpdateAvailable

### ISSUE THREAD

**Issue by gasolin** [umbertoghio/expo-custom-updater#3]
@siapdev thanks for your module, it saves us a lot of effort to handle the Expo update process.
Checked the code and just wanna share some suggestions to further improve the package

According to https://github.com/umbertoghio/expo-custom-updater/blob/master/index.js#L67

`skipTimeCheck` param is not used in isAppUpdateAvailable

**Comment by umbertoghio** [comment]
Thank you! :-) 
Fixed in ea4f443736f35d68cd9ad3c7f01e3bc38d18c885
