### ISSUE TITLE
throw new Error in catch

### ISSUE THREAD

**Issue by gasolin** [umbertoghio/expo-custom-updater#4]
besides only do this.log in catch sentence
https://github.com/umbertoghio/expo-custom-updater/blob/master/index.js#L99

It will be nice to also do `throw new Error(e.message)`
Therefore the module user can catch the propagate error in the their code

**Comment by umbertoghio** [comment]
Hi, 
it's a good idea, but take care in handling the exception properly as it could end up in an app crash / restart / update / crash endless loop.
I've added an option in the constructor throwUpdateErrors, set it to true and you'll get the exception, I've published version 1.0.10 in npm
