### ISSUE TITLE
is this only work for class component?

### ISSUE THREAD

**Issue by gabielchong** [umbertoghio/expo-custom-updater#8]
sorry I am not familiar with react native, is this work for function component?

**Comment by umbertoghio** [comment]
Hi, yes, you can use it in functional component, suggest to use it in your top-most component (app.js or similar), you can use then a useEffect / useEffect Cleanup as equivalent of component will mount and componendo did unmount.

Or you can skip the app state check and just force an update on startup if present

**Comment by umbertoghio** [comment]
Closing this out
